services:
  postgres:
    image: postgres:16.12-bookworm
    container_name: sqlalchemy-pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sqlalchemy_db
    ports:
      - "5432:5432"
    networks:
      - sandbox-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sqlalchemy_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: sqlalchemy-app
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./app:/app
    command: python app.py
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=sqlalchemy_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "5003:5000"
    networks:
      - sandbox-network

networks:
  sandbox-network:
    #external: true # Внешняя сеть. sudo docker network create sandbox-network
    driver: bridge

volumes:
  pg_data:
  app: