services:
  app:
    build: .
    container_name: python-sandbox
    environment:
      - FLASK_ENV=development
      # Вывод сразу на экран
      - PYTHONUNBUFFERED=True                   
    ports:
      - "5001:5000"
    volumes:
      - ./app:/app
    command: tail -f /dev/null # чтобы контейнер не завершался
    #command: python app.py
    networks:
      - sandbox-network

volumes:
  app:

networks:
  sandbox-network:
    #external: true # Внешняя сеть. sudo docker network create sandbox-network
    driver: bridge